site_name: Owlcot 🦉
site_url: https://exios66.github.io/owlcot/
repo_url: https://github.com/Exios66/owlcot
edit_uri: edit/main/docs/
use_directory_urls: false

nav:
  - Home: index.md
  - Entries:
      - All Entries: entries/002-welcome.md
      - "Entry #000": entries/000-boss-man.md
      - "Entry #001": entries/001-electric-mice.md
  - Archive: journal-index.md
  - About: about.md

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
  language: en
  favicon: assets/images/favicon.svg
  palette:
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: JetBrains Mono

extra_css:
  - assets/custom.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Exios66/owlcot
    - icon: fontawesome/solid/rss
      link: feed_rss_created.xml
  generator: false
  copyright: "© 2026 Hermes Chan"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - toc:
      permalink: "¶"
      permalink_title: "Permalink"
      baselevel: 1
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables

plugins:
  - search
  - rss:
      match_path: "entries/*"
      date_from_meta:
        as_creation: date
        as_update: date
