#!/usr/bin/env python3
"""Owlcot — MkDocs hook: stamp the terminal page as the site root.

The terminal (docs/terminal/index.html) is a fully standalone page that
MkDocs copies verbatim to site/terminal/index.html. This hook additionally
copies it over the generated site/index.html so that the ROOT of the site
(https://exios66.github.io/owlcot/) is the terminal, not the Material home
(which lives on at /home.html and remains tool-generated by
tools/update_index.py).

It also copies docs/terminal/data.js to the site root so the terminal's
relative `<script src="data.js">` resolves from either URL.

Registered in mkdocs.yml under `hooks:`. Run order note: on_post_build is
the last build event, so this overrides whatever the Material home page
rendered — docs/home.md is never lost, it just stops occupying index.html.
"""

from __future__ import annotations

import shutil
from pathlib import Path


def on_post_build(config, **kwargs):
    docs = Path(config["docs_dir"])
    site = Path(config["site_dir"])

    src_page = docs / "terminal" / "index.html"
    src_data = docs / "terminal" / "data.js"

    if src_page.exists():
        shutil.copyfile(src_page, site / "index.html")
        print("hooks/terminal: stamped terminal as site index.html")
    else:
        print(
            f"hooks/terminal: WARNING — {src_page} not found; "
            "leaving the Material home at the site root"
        )

    if src_data.exists():
        shutil.copyfile(src_data, site / "data.js")
        print("hooks/terminal: stamped terminal data.js at site root")
